### ISSUE TITLE
Text height

### ISSUE THREAD

**Issue by benjaminwork** [ghepting/jquery-responsive-text#1]
I've got this working well on my site, but in trying to make my site fully responsive, I want everything to resize for height as well as width.
When I have a header set to responsive, it works well when I change width, but doesn't change at all when the browser height changes and doesn't allow me to choose a new height in css media queries.

**Comment by ghepting** [comment]
It isn't currently setup to react to vertical constraints at all as that hasn't been a use-case anyone (including myself) has ever indicated would be useful, but I'm sure it wouldn't be hard to extend it to do that.

What functionality would you expect or propose for a feature like this? I'm not even sure that I can picture a scenario where you would care about the vertical space versus the text fitting on one line.

**Comment by benjaminwork** [comment]
Hi. Thanks for responding.
I'm trying to build a fully responsive website and the whole site is made up of different divs that all have heights and widths in %.
That means that using your plugin, whenever I make the browser narrower or wider, the text fits perfectly. If however a user has a shorter (in height) screen, such as a widescreen laptop, the divs use up the same proportions because the height was set as a %, but the text overflows the div. I know I can use media queries to change the layout at various break points, but for width, the plugin is much more seamless and easy to code than writing loads of breakpoints!

Thanks. Hope that all makes sense

**Comment by ghepting** [comment]
Yeah, I get the general gist of what you're saying -- you want it to cap out the font size based on the vertical space available as well, but what would you expect the functionality to be? Limiting a container's vertical height is naturally going to lead to less fluid and flexible layout, but I'm not convinced that reducing a line of text's horizontal span is really enhancing user experience or increasing the integrity of a layout...
